module.exports = {
    EXPIRED: 'expired',
    EXPIRE: 'expire',
    DEL: 'del',
    SET: 'set',
    SORT: 'sortstore',
    SETRANGE: 'setrange',
    INCRBY: 'incrby',
    INCRBYFLOAT: 'incrbyfloat',
    APPEND: 'append',
    LPUSH: 'lpush',
    RPUSH: 'rpush',
    RPOP: 'rpop',
    LPOP: 'lpop',
    LINSERT: 'linsert',
    LSET: 'lset',
    LREM: 'lrem',
    LTRIM: 'ltrim',
    HSET: 'hset',
    HINCRBY: 'hincrby',
    HINCRBYFLOAT: 'hincrbyfloat',
    HEDL: 'hdel',
    SADD: 'sadd',
    SREM: 'srem',
    SPOP: 'spop'
};